language: php

cache:
  directories:
    - $HOME/.composer/cache

php:
  - 5.5
  - 5.6
  - 7.0

before_install:
  - travis_retry composer self-update

install:
  - travis_retry composer update --no-interaction

script:
  - composer test-ci

after_success:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover build/logs/clover.xml
